git:
  paging:
    colorArg: always
    # Respect .gitconfig 
    useConfig: true
keybinding:
  universal:
    scrollUpMain: 'I' # main panel scroll up
    scrollDownMain: 'U' # main panel scroll down
